### ISSUE TITLE
Define features & monetization

### ISSUE THREAD

**Issue by jdvr** [jdvr/exercise-tracker-bot#1]
# Vision:

> Una aplicación para llevar el control de tu ejercicicio y evolución comporal. Sencilla de usar y con soporte para lenguaje natural.

# Monetizacion

- Gratis
  - 5 sesiones
  - Max dos pesos
  - Reinicio de la cuenta cada 3 mes
- Pago único
  - Pago por una sesion de calentamiento dictada a la semana
  - Registra hasta 1 sesion al dia por lenguaje natural
- Subsctiption
  - Usar IA sin limite

# Roadmap

## Empezar a usar

- [ ] Registrar sesion
    - Distancia
    - Tiempo
    - Pasos
- [ ] Registrar peso

## Registro completo

- [ ] Registrar más medidas

## Soporte lenguaje natural

- [ ] Registrar sisiones con lenguaje natural
- [ ] Registar medidas con lenguaje natural
- [ ] Registrar seiciones con capturas

## Monetization

- [ ] Añadir monetizacion
  - Gestion de cuotas (rate limiting)
  - Gestiion de pago únicod
  - Gestion de suscripción

## Calentamiento

- [ ] Añadir base de dato de ejericios de calentamiento
- [ ] Generar sesiones de calentaiento
- [ ] Dictar sesiones de calentamiento

## Graficas y estadisticas

- [ ] Graficas y estadisticas de la sesiones
- [ ] Graficas y estadisticas personales
    - Medidas (peso, altura, etc)

## Retos

- [ ] Establecer metas
  - Cambio de peso
  - Distancia
  - Num de sesiones
- [ ] Recordatorios [diarios, semanales, mensuales]
- [ ] Seguir progreso de las metas después de cada sesión (registro)

## Soporte para gym

- [ ] Añadir sesiones de gymnasio
    - Ejercicio
    - Series
        - Peso
        - Repeticiones

**Comment by jdvr** [comment]
I discard complex exercises because I don't want to display images or videos .

I am pivoting to exercise tracking .

Inspiration https://gymkeeper.app/

**Comment by jdvr** [comment]
Medidas:

- Altura
- Peso
- Cuello
- Brazo
- Pecho
- Cintura 
- Muslo (ingle)
- Muslo (rodilla)
- Cadera

**Comment by jdvr** [comment]
Vision:

> registrar sesiones de ejericio y medidas personales

# Empezar a usar

- [ ] Registrar sesion
    - Distancia
    - Tiempo
    - Pasos 
- [ ] Registrar peso

# Registro completo

- [ ] Registrar más medidas

# Soporte lenguaje natural

- [ ] Registrar sisiones con lenguaje natural
- [ ] Registar medidas con lenguaje natural
- [ ] Registrar seiciones con capturas

# Calentamiento

- [ ] Añadir base de dato de ejericios de calentamiento
- [ ] Generar sesiones de calentaiento
- [ ] Dictar sesiones de calentamiento

# Graficas y estadisticas

- [ ] Graficas y estadisticas de la sesiones
- [ ] Graficas y estadisticas personales
  - Medidas (peso, altura, etc)

# Soporte para gym

- [ ] Añadir sesiones de gymnasio
  - Ejercicio
  - Series
    - Peso
    - Repeticiones
